# https://beta.ruff.rs
name: Ruff linter
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ruff-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Ruff Check
        run: ruff check .
